name: BeatzPro
description: A app for music streaming.
version: 1.10.0+16

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_links: ^3.5.1
  archive: ^3.1.6
  audio_service: ^0.18.15
  audio_service_mpris: ^0.1.5
  audio_video_progress_bar: ^2.0.3
  audiotags: ^1.4.1
  buttons_tabbar: ^1.3.13
  cached_network_image: ^3.4.0
  carousel_animations: ^0.0.4
  device_equalizer:
    git:
      url: https://github.com/anandnet/device_equalizer.git
      ref: 29ea7ff4e284101af114de64bafca25a1a0c01d8
  dio: ^5.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_lyric: ^2.0.4+6
  flutter_slidable: ^3.1.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ionicons: ^0.2.2
  just_audio: ^0.9.40
  just_audio_media_kit:
    git:
      url: https://github.com/anandnet/just_audio_media_kit.git
      ref: 06de226da469f5c55dd780b215bcc45a0d6269fb
  logger: ^2.4.0
  palette_generator: ^0.3.3+4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  player_response:
    git:
      url: https://github.com/anandnet/Player-Response.git
      branch: main
      ref: d7244f52d427b4aabde57be404d4316474613508
  restart_app: ^1.2.1
  sdk_int:
    git:
      url: https://github.com/anandnet/sdk_int.git
      ref: 91b2d4e0863de4effb2c89dd7868506cbd85a1ee
  share_plus: ^9.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sidebar_with_animation:
    git:
      url: https://github.com/anandnet/animated_side_bar.git
      branch: main
      ref: b53567a42b4ba3793a3cf00d478bdba0ecce33d7
  smtc_windows: ^0.1.2
  toggle_switch: ^2.1.0
  tray_manager: ^0.2.3
  url_launcher: ^6.2.1
  widget_marquee: ^0.0.8
  window_manager: ^0.4.2
dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ico.png"
  adaptive_icon_background: "#FFFFFF" # Solo para Android
  adaptive_icon_foreground: "assets/icons/ico.png" # Solo para Android
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/


